source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'
pod 'AFNetworking'
pod 'NSLogger'
pod 'MMProgressHUD'
pod 'UIColor-Hex'
pod 'UIImage+ImageWithColor'
pod 'pop'
pod 'GZIP'
pod 'SDWebImage'
